
name: brahm-testing/lambda-galaxy
description: tasks for creating & invoking a lambda for generating a galaxy

parameters:
  lambda_host:
    required: false
    description: the hostname for the lambda service
  lambda_region:
    required: true
    default: us-east-2
    description: the lambda region to interact with
  function_name:
    default: galaxy
    description: the name for the lambda function
  lambda_role:
    required: true
    default: foobar
    description: the role the lambda will be executed as

services:
  lambda:
    image: localstack/localstack:0.12.17.5
    interfaces:
      lambda:
        host: ${{ parameters.lambda_host }}
        protocol: https
        port: 443
    environment:
      SERVICES: lambda
    debug:
      interfaces:
        lambda:
          protocol: http
          port: 4566

tasks:
  create-function:
    schedule: ""
    build:
      context: .
    command: >-
      --region ${{ parameters.lambda_region }}
      --endpoint ${{ services.lambda.interfaces.lambda.url }}
      lambda create-function
      --zip-file fileb:///root/lambda.zip
      --function-name ${{ parameters.function_name }}
      --runtime nodejs12.x
      --timeout 30
      --memory-size 512
      --role ${{ parameters.lambda_role }}
      --handler lambda.handler
    depends_on:
      - lambda
    # mounting local dir into prod config just for local testing
    volumes:
      aws_credentials:
        description: Mount aws credentials into the aws-cli
        host_path: /Users/sk4ly/.aws
        mount_path: /root/.aws
    debug:
      volumes:
        aws_credentials:
          description: Mount aws credentials into the aws-cli
          host_path: /Users/sk4ly/.aws
          mount_path: /root/.aws

  generate:
    schedule: ""
    image: amazon/aws-cli:2.1.32
    command: >-
      --region ${{ parameters.lambda_region }}
      --endpoint ${{ services.lambda.interfaces.lambda.url }}
      lambda invoke
      --function-name ${{ parameters.function_name }}
      --log-type None
      /dev/stdout
    depends_on:
      - lambda
    # mounting local dir into prod config just for local testing
    volumes:
      aws_credentials:
        description: Mount aws credentials into the aws-cli
        host_path: /Users/sk4ly/.aws
        mount_path: /root/.aws
    debug:
      volumes:
        aws_credentials:
          description: Mount aws credentials into the aws-cli
          host_path: /Users/sk4ly/.aws
          mount_path: /root/.aws
